Repository heig-PRO-b04/elm-frontend, pull requests merged in 2020-05, with the labels that each got.

#143 Add an Html.Attribute for enter key events
  src/Html/Events/Extra.elm
  src/Page/Authenticate.elm
Labels: waiting-for-review

#140 Implement first iteration of answers api
  src/Api/Answers.elm
Labels: waiting-for-review

#144 Rework the Session user interface
  src/Page/Poll/Session.elm
  src/Page/Poll/Session/Emoji.elm
Labels: waiting-for-review

#145 Update the poll title edit screen
  src/Page/Poll.elm
  src/Picasso/Button.elm
Labels: waiting-for-review

#146 Add API support for indexInPoll
  src/Api/Questions.elm
  src/Json/Decode/Extra.elm
  src/Page/Poll/Questions.elm
Labels: waiting-for-review

#148 Rework the question list
  src/Page/Poll/Questions.elm
Labels: waiting-for-review

#149 Rename wrongfully named module
  src/Api/Answers.elm
Labels: waiting-for-review

#150 Add support for drag and drop
  elm.json
  src/Page/Poll/Questions.elm
Labels: waiting-for-review

#165 Try to implement basic answer creation in submodel
  src/Page/Answers.elm
  src/Page/Poll.elm
  src/Page/Question.elm
  src/Page/QuestionList.elm
Labels: waiting-for-review

#164 Remove the Header source file
  src/Header.elm
Labels: waiting-for-review

#167 Implement a nicer GUI to create, delete and mock update answers
  src/Api/Answers.elm
  src/Page/Answers.elm
Labels: waiting-for-review

#168 Non-deterministic seed generation and nicer expand
  src/Page/QuestionList.elm
  static/icon/chevron-right.svg
Labels: waiting-for-review

#169 Add a tray to filter questions by visibility
  src/Page/QuestionList.elm
  src/Page/QuestionList/Visibility.elm
  static/icon/filter-variant.svg
Labels: waiting-for-review

#170 Add some toggles for visibility
  src/Page/QuestionList.elm
  static/icon/visibility-archive.svg
  static/icon/visibility-hide.svg
  static/icon/visibility-show.svg
  static/icon/visibility-unarchive.svg
Labels: waiting-for-review

#173 Add some simple statistics
  elm.json
  src/Api/Statistics.elm
  src/Page/Poll.elm
  src/Page/PollStatistics.elm
  src/Page/PollStatistics/Charts.elm
  src/Page/QuestionList.elm
Labels: waiting-for-review

#171 Make a pretty GUI to modify answers
  src/Page/Answers.elm
  static/icon/pencil.svg
Labels: waiting-for-review

#174 A few GUI fixes and some improvements
  src/Page/Answers.elm
  src/Page/Answers/Indices.elm
  src/Page/Poll.elm
  src/Page/PollStatistics.elm
  src/Page/PollStatistics/Charts.elm
  src/Page/QuestionList.elm
  src/Picasso/Navigation.elm
Labels: waiting-for-review

#177 Remove Answers model from collapsed questions
  src/Page/QuestionList.elm
Labels: waiting-for-review

#179 Add reloading answers
  src/Page/Answers.elm
  src/Page/Poll.elm
  src/Page/QuestionList.elm
Labels: waiting-for-review

#182 Add live question statistics
  elm.json
  src/Api/QuestionStatistics.elm
  src/Page/QuestionList.elm
  src/Page/QuestionStatistics.elm
  static/icon/statistics-hide.svg
  static/icon/statistics-show.svg
Labels: waiting-for-review

#183 Add basic question modification
  src/Page/Answers.elm
  src/Page/QuestionList.elm
Labels: waiting-for-review

#184 Prettify question details, make things more mobile friendly
  src/Page/Answers.elm
  src/Page/QuestionList.elm
Labels: waiting-for-review

#185 min/max answers modification, prevent modification of question while displaying stats
  src/Page/Answers.elm
  src/Page/QuestionList.elm
Labels: waiting-for-review

#187 Quality of life improvements
  src/Page/Answers.elm
  src/Page/Authenticate.elm
  src/Page/Poll.elm
  src/Page/PollList.elm
  src/Page/QuestionList.elm
Labels: wip

#188 Implement the account management API specification
  src/Api/Account.elm
Labels: waiting-for-review

#190 Improve the account management GUI
  src/Page/Account.elm
Labels: waiting-for-review

#191 Add Selenium and run it automatically in CI
  .github/workflows/integration-tests.yml
  Dockerfile
  integration-tests/await-website.py
  integration-tests/docker-compose.yml
  integration-tests/src/simpletest.py
  src/Api.elm
Labels: waiting-for-review

#192 Remove Elm make from Dockerfile
  Dockerfile
Labels: waiting-for-review

#193 Add a badge for integration tests
  README.md
Labels: waiting-for-review

#195 Add elm-analyse and fix the project
  .github/workflows/format.yml
  elm.json
  package.json
  src/Api.elm
  src/Api/Polls.elm
  src/Api/Questions.elm
  src/Api/Sessions.elm
  src/List/Extra.elm
  src/Main.elm
  src/Page/Answers.elm
  src/Page/Answers/Indices.elm
  src/Page/Authenticate.elm
  src/Page/BadCredentials.elm
  src/Page/Home.elm
  src/Page/Logout.elm
  src/Page/Poll.elm
  src/Page/Poll/Session.elm
  src/Page/PollList.elm
  src/Page/PollLive.elm
  src/Page/PollStatistics/Charts.elm
  src/Page/QuestionList.elm
  src/Page/QuestionStatistics.elm
  src/Picasso/Input.elm
  src/Picasso/Navigation.elm
  src/Route.elm
  yarn.lock
Labels: quality-assurance

#196 Move and rename Cmd and withCmd
  src/Cmd/Extra.elm
  src/Main.elm
  src/Page/Answers.elm
  src/Page/Authenticate.elm
  src/Page/BadCredentials.elm
  src/Page/Home.elm
  src/Page/Logout.elm
  src/Page/Poll.elm
  src/Page/Poll/Session.elm
  src/Page/PollList.elm
  src/Page/QuestionList.elm
  src/Page/QuestionStatistics.elm
  src/Picasso/Navigation.elm
Labels: waiting-for-review

#197 Add a SelectableItemList
  elm.json
  src/Page/Answers.elm
  src/Page/QuestionList.elm
  src/SelectableItemList.elm
Labels: waiting-for-review

#198 Add a toggle for question visibility on creation
  src/Page/QuestionList.elm
Labels: waiting-for-review

#199 Add a help page skeleton
  src/Main.elm
  src/Page/Help.elm
  src/Picasso/Navigation.elm
  src/Route.elm
  static/img/newPoll.png
Labels: waiting-for-review

#200 Fix improper wording for account updates
  src/Page/Account.elm
Labels: waiting-for-review

#201 Use purge-css in production
  package.json
  postcss.config.js
  yarn.lock
Labels: waiting-for-review

#202 Revert "Use purge-css in production"
  package.json
  postcss.config.js
  yarn.lock
Labels: bug, waiting-for-review

#203 Update the help page layout
  src/Page/Help.elm
Labels: waiting-for-review

#205 Beautify the home page
  src/Page/Home.elm
  static/icon/arrow-right.svg
Labels: waiting-for-review

#207 Improve authentication messages based on user feedback
  src/Page/Authenticate.elm
Labels: waiting-for-review

#208 Add some production assets
  src/Page/Help.elm
  src/Page/Help/Content.elm
  src/Page/Home.elm
  static/help/create-poll.gif
  static/help/create-question.gif
  static/help/open-poll.gif
  static/help/polls-all.png
  static/help/polls-new.png
  static/help/questions-1.png
  static/help/stats-1.png
  static/help/stats-2.png
  static/help/voting-1.png
  static/help/voting-2.png
  static/img/logo.png
  static/img/newPoll.png
  tailwind.config.js
Labels: waiting-for-review

#206 Insert questions at the top of the list
  src/Page/QuestionList.elm
Labels: waiting-for-review

#211 Add new integration tests
  .github/workflows/integration-tests.yml
  integration-tests/src/README.md
  integration-tests/src/register_full.py
  integration-tests/src/register_update_profile.py
  integration-tests/src/simpletest.py
Labels: waiting-for-review

#212 Add basic module documentation for every elm module
  src/Api/Account.elm
  src/Api/QuestionStatistics.elm
  src/Api/Sessions.elm
  src/Api/Statistics.elm
  src/Cmd/Extra.elm
  src/Html/Events/Extra.elm
  src/Json/Decode/Extra.elm
  src/List/Extra.elm
  src/Main.elm
  src/Page/Account.elm
  src/Page/Answers.elm
  src/Page/Answers/Indices.elm
  src/Page/BadCredentials.elm
  src/Page/Help.elm
  src/Page/Help/Content.elm
  src/Page/Home.elm
  src/Page/Logout.elm
  src/Page/Poll.elm
  src/Page/Poll/Session.elm
  src/Page/Poll/Session/Emoji.elm
  src/Page/PollList.elm
  src/Page/PollList/Sorting.elm
  src/Page/PollLive.elm
  src/Page/PollStatistics.elm
  src/Page/PollStatistics/Charts.elm
  src/Page/QuestionList.elm
  src/Page/QuestionList/Visibility.elm
  src/Page/QuestionStatistics.elm
  src/Picasso/FloatingButton.elm
  src/Picasso/Input.elm
  src/Picasso/Text.elm
  src/Route.elm
  src/Task/Extra.elm
Labels: documentation, waiting-for-review

#217 Add documentation for exposed functions
  src/Api/Answers.elm
  src/Api/Polls.elm
  src/Api/Questions.elm
  src/Api/Sessions.elm
  src/Html/Events/Extra.elm
  src/Json/Decode/Extra.elm
  src/List/Extra.elm
  src/Page/Account.elm
  src/Page/Answers.elm
  src/Page/Authenticate.elm
  src/Page/BadCredentials.elm
  src/Page/Help.elm
  src/Page/Help/Content.elm
  src/Page/Home.elm
  src/Page/Logout.elm
  src/Page/Poll.elm
  src/Page/Poll/Session.elm
  src/Page/Poll/Session/Emoji.elm
  src/Page/PollList/Sorting.elm
  src/Page/PollLive.elm
  src/Page/PollStatistics.elm
  src/Page/PollStatistics/Charts.elm
  src/Page/QuestionList.elm
  src/Page/QuestionList/Visibility.elm
  src/Page/QuestionStatistics.elm
  src/Picasso/FloatingButton.elm
  src/Picasso/Input.elm
  src/Picasso/Navigation.elm
  src/Picasso/Text.elm
  src/Route.elm
  src/SelectableItemList.elm
  src/Session.elm
Labels: documentation
