Repository heig-PRO-b04/elm-frontend, pull requests merged in 2020-04, with the labels that each got.

#32 Enforce authentication for user-defined endpoints
  src/Api.elm
Labels: waiting-for-review

#34 Add a landing page
  src/Main.elm
  src/Page/Home.elm
  src/Picasso/Text.elm
  yarn.lock
Labels: ep : 3, waiting-for-review

#44 Implement a logout action in the navigation bar
  src/Main.elm
  src/Page/Logout.elm
  src/Picasso/Navigation.elm
  src/Route.elm
Labels: wip

#50 Integrate GitHub Actions in the project
  .github/workflows/deploy.yml
  .github/workflows/format.yml
  .github/workflows/unit-tests.yml
  .travis.yml
  package.json
Labels: waiting-for-review

#52 Store moderator's id in credentials and add a function to get poll list
  src/Api.elm
  src/Api/Polls.elm
Labels: waiting-for-review

#54 Update README.md shields for the new CI
  README.md
Labels: waiting-for-review

#56 Add an issue template for Tasks we're working on
  .github/ISSUE_TEMPLATE/task.md
Labels: waiting-for-review

#57 Run GitHub workflows on pull requests
  .github/workflows/format.yml
  .github/workflows/unit-tests.yml
Labels: waiting-for-review

#58 Enforce line length, and slightly alter names
  src/Api/Polls.elm
Labels: waiting-for-review

#60 Add a skeleton for the Polls page
  src/Main.elm
  src/Page/Authenticate.elm
  src/Page/Polls.elm
  src/Picasso/Navigation.elm
  src/Route.elm
Labels: waiting-for-review

#62 Fix the Task issue template format
  .github/ISSUE_TEMPLATE/task.md
Labels: waiting-for-review

#63 Close the navigation menu on route changes
  src/Picasso/Navigation.elm
Labels: waiting-for-review

#65 Fix dropdown
  src/Picasso/Navigation.elm
  src/Picasso/Text.elm
Labels: waiting-for-review

#70 Display a mocked list of polls
  src/Page/Polls.elm
Labels: waiting-for-review

#73 Add a temporary poll creation page
  src/Main.elm
  src/Page/NewPoll.elm
  src/Picasso/Navigation.elm
  src/Route.elm
Labels: wip

#75 Implement PUT and DELETE methods for Api
  src/Api.elm
Labels: waiting-for-review

#77 Implement a Viewer module and use it on the Polls page
  src/Main.elm
  src/Page/Authenticate.elm
  src/Page/Logout.elm
  src/Page/Polls.elm
  src/Picasso/Navigation.elm
  src/Session.elm
Labels: waiting-for-review

#78 Fix #71 by properly resetting fields
  src/Page/Authenticate.elm
Labels: waiting-for-review

#79 Implement poll deletion
  src/Api.elm
  src/Api/Polls.elm
  src/Cmd.elm
  src/Page/Polls.elm
Labels: waiting-for-review

#80 Add a functional create new poll page
  src/Api/Polls.elm
  src/Main.elm
  src/Page/NewPoll.elm
Labels: waiting-for-review

#82 Improve layouts on mobile
  src/Page/Polls.elm
  src/Picasso/Navigation.elm
Labels: waiting-for-review

#86 Change route on page start, based on the provided url
  src/Cmd.elm
  src/Main.elm
Labels: waiting-for-review

#84 Refine the polls display page
  elm.json
  src/Cmd.elm
  src/Main.elm
  src/Page/Polls.elm
  src/Page/Polls/Sorting.elm
  static/icon/arrow-down.svg
  static/icon/arrow-up.svg
Labels: waiting-for-review

#93 Make some miscellaneous GUI improvements.
  src/Page/Polls.elm
  src/Picasso/FloatingButton.elm
  src/Picasso/Navigation.elm
  static/icon/arrow-up.svg
  tailwind.config.js
Labels: waiting-for-review

#94 Add a Page and Route for credentials errors
  src/Main.elm
  src/Page/BadCredentials.elm
  src/Route.elm
Labels: waiting-for-review

#95 Try to fix #42 with localStorage redirection
  index.js
  src/Api.elm
  static/404.html
  static/404.js
Labels: waiting-for-review

#97 Disconnect on credentials invalidation
  src/Page/Polls.elm
Labels: waiting-for-review

#98 Add a way to change existing poll titles
  src/Api/Polls.elm
  src/Page/NewPoll.elm
Labels: waiting-for-review

#104 Implement navigation to polls
  src/Page/Polls.elm
  tailwind.config.js
Labels: waiting-for-review

#105 Add a Session API and endpoints, plus display the sessions statuses on the polls screen
  src/Api/Sessions.elm
  src/Page/Polls.elm
Labels: waiting-for-review

#108 Polldetails refinements
  src/Page/DisplayPoll.elm
Labels: waiting-for-review

#111 Display SessionStatus in the poll details
  elm.json
  src/Api/Sessions.elm
  src/Main.elm
  src/Page/DisplayPoll.elm
Labels: wip

#114 Try to fix pages refreshes not working in nested hierarchies
  static/404.html
Labels: bug, waiting-for-review

#115 Fix a bug where question init commands are ignored
  src/Page/DisplayPoll.elm
Labels: bug, waiting-for-review

#116 Move the session management to its own component
  src/Page/DisplayPoll.elm
  src/Page/DisplayPoll/Session.elm
Labels: waiting-for-review

#117 Drastically improve the session UI
  elm.json
  src/Api/Sessions.elm
  src/Page/DisplayPoll.elm
  src/Page/DisplayPoll/Session.elm
  src/Page/DisplayPoll/Session/Emoji.elm
Labels: waiting-for-review

#122 Fix CI failing on forks
  .github/workflows/deploy.yml
Labels: waiting-for-review

#124 Automate Telegram notification for pull request reviews
  .github/workflows/ready-for-review.yml
Labels: waiting-for-review

#126 Fix token not working
  .github/workflows/ready-for-review.yml
Labels: waiting-for-review

#125 Fix 404.html formatting
  static/404.html
Labels: waiting-for-review

#127 Remove tokens (and revoke them)
  .github/workflows/ready-for-review.yml
Labels: waiting-for-review

#123 Display session information in a participants page
  src/List/Extra.elm
  src/Main.elm
  src/Page/DisplayPoll.elm
  src/Page/DisplayPoll/Session.elm
  src/Page/PollLive.elm
  src/Picasso/Navigation.elm
  src/Route.elm
Labels: waiting-for-review

#128 Display a basic list of questions for a poll
  src/Api/Questions.elm
  src/Page/DisplayPoll.elm
  src/Page/DisplayPoll/Questions.elm
Labels: waiting-for-review

#130 Refactor module names and add a Question page
  src/Api/Polls.elm
  src/Main.elm
  src/Page/Poll.elm
  src/Page/Poll/Questions.elm
  src/Page/Poll/Session.elm
  src/Page/Poll/Session/Emoji.elm
  src/Page/PollList.elm
  src/Page/PollList/Sorting.elm
  src/Page/PollLive.elm
  src/Page/Question.elm
Labels: waiting-for-review

#133 Use a list of questions submodels
  src/Page/Poll/Questions.elm
  src/Page/Question.elm
Labels: waiting-for-review

#135 Add question view table rows
  src/Page/Question.elm
Labels: waiting-for-review

#136 Add misc. improvements to the poll screen
  src/Page/Poll/Questions.elm
Labels: waiting-for-review

#137 Beautify subquestion view
  src/Api/Questions.elm
  src/Page/Question.elm
Labels: waiting-for-review

#138 Change the question list background color
  src/Page/Poll/Questions.elm
Labels: waiting-for-review

#139 Make the question input inline
  src/Page/Poll/Questions.elm
Labels: waiting-for-review
